### ISSUE TITLE
Label U2OS cells

### ISSUE THREAD

**Issue by siriusstarzx** [CellProfiling/HPA-Cell-Segmentation#27]
Hi,

I tried to segment U2OS cells with HPA-cell-Segmentation, but could not get good results(As you can see from the image). I think the reason is that U2OS cells are smaller than normal cells. I have tried to change the scale_factor or resize the image according to the HPA dataset, but without any improvement. I would like to ask, do you have any suggestions to achieve better segmentation?
![mask](https://user-images.githubusercontent.com/96951760/211281895-cc51388a-f301-43d6-836f-2ec8a8bffced.png)

Thanks in advance and happy new year!

Best regards,
Xin.

**Comment by cwinsnes** [comment]
Hello Xin!

The model has worked well for U-2 OS cells before, but I believe we have only tested it on data from the HPA.

My spontaneous guess is that the issue here is that your image contains much smaller cells (in terms of pixel area per cell) than what the model has originally been trained for. You might need to retrain the model for your specific case by manually labeling some images and using that as training data. As the model is already trained on similar data, it should require much less training data than if you were to train the model from scratch.

Another possibility could be to upscale your images to make sure that the pixels represent the same distances as in the HPA (`0.08μm` per pixel), but I am unsure on how well this would work in practice.

Best regards,
Casper

**Comment by siriusstarzx** [comment]
Hi Casper,

Thanks for your reply and your explanation!

According to your suggestions, I have tried to upscale my images and make the pixels represent the same distances as in the HPA. At present, the segmentation is much better!

Thank you once again!
Xin.

**Comment by cwinsnes** [comment]
Awesome! Let me know if there are any other issues that you find. I will close this issue for now.
